 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

//basic required import for NodeJs
const express = require("express");
const bodyParser = require("body-parser");
const cors = require("cors");
const mongoose = require('mongoose')
const Bing = require('node-bing-api')({accKey: 'db6'});

const app = express();
app.use(bodyParser.json());
app.use(cors());
//get call to return JSON that format natural and unix data
app.get('/dateValues/:dateVal', function(req, res, next){
    console.log('url works');
    var dateVal = req.params.dateVal;
    var dataFormattingOptions = {
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    };
    
    if(isNaN(dateVal)){
        var naturalDate = new Date(dateVal);
        naturalDate = naturalDate.toLocaleDateString("en-us", dataFormattingOptions);
        var unixDate = new Date(dateVal).getTime()/1000;
    }
    else{
        var unixDate = dateVal;
        var naturalDate = new Date(dateVal *1000);
        naturalDate = naturalDate.toLocaleDateString("en-us", dataFormattingOptions);
    }
    res.json({unix: unixDate, natural: naturalDate});
});

app.get("/", function (request, response) {
  response.sendFile(__dirname + '/views/index.html');
});

app.listen(process.env.PORT || 3000, function(){
    console.log("this server is  working");
});
