 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

//basic required import for NodeJs
const express = require("express");
const bodyParser = require("body-parser");
const cors = require("cors");
const mongoose = require('mongoose')
const Bing = require('node-bing-api')({accKey: 'b0b514c15b824f02838009ea17a7ec84'});

const app = express();
app.use(bodyParser.json());
app.use(cors());
//get call to return JSON that format natural and unix data
app.get('/api/imagesearch/:searchVal*', (req, res, next) => {
  var {searchVal} = req.params
  var  {offset}  = req.query
  res.json({
    searchVal,
    offset
  });  
  
    
    
});



app.listen(process.env.PORT || 3000, function(){
    console.log("this server is  working on " + process.env.PORT);
});
